namespace BoletoNet
{
    internal enum TipoOcorrencia
    {
      //Ocorrências para arquivo remessa
      RemRegistrar, //Registrar o título no banco
      RemBaixar, //Baixar o título no banco
      RemDebitarEmConta,
      RemConcederAbatimento,
      RemCancelarAbatimento,
      RemConcederDesconto,
      RemCancelarDesconto,
      RemAlterarVencimento,
      RemProtestar,
      RemCancelarInstrucaoProtesto,
      RemDispensarJuros,
      RemAlterarNomeEnderecoSacado,
      RemAlterarNumeroControle,
      RemOutrasOcorrencias,

      //Ocorrências para arquivo retorno
      RetRegistroConfirmado,
      RetRegistroRecusado,
      RetComandoRecusado,
      RetLiquidado,
      RetLiquidadoEmCartorio,
      RetLiquidadoParcialmente,
      RetLiquidadoSaldoRestante,
      RetLiquidadoSemRegistro,
      RetLiquidadoPorConta,
      RetBaixaSolicitada,
      RetBaixado,
      RetBaixadoPorDevolucao,
      RetBaixadoFrancoPagamento,
      RetBaixaPorProtesto,
      RetRecebimentoInstrucaoBaixar,
      RetBaixaOuLiquidacaoEstornada,
      RetTituloEmSer,
      RetRecebimentoInstrucaoConcederAbatimento,
      RetAbatimentoConcedido,
      RetRecebimentoInstrucaoCancelarAbatimento,
      RetAbatimentoCancelado,
      RetRecebimentoInstrucaoConcederDesconto,
      RetDescontoConcedido,
      RetRecebimentoInstrucaoCancelarDesconto,
      RetDescontoCancelado,
      RetRecebimentoInstrucaoAlterarDados,
      RetDadosAlterados,
      RetRecebimentoInstrucaoAlterarVencimento,
      RetVencimentoAlterado,
      RetAlteracaoDadosNovaEntrada,
      RetAlteracaoDadosBaixa,
      RetRecebimentoInstrucaoProtestar,
      RetProtestado,
      RetRecebimentoInstrucaoSustarProtesto,
      RetProtestoSustado,
      RetInstrucaoProtestoRejeitadaSustadaOuPendente, 
      RetDebitoEmConta,
      RetRecebimentoInstrucaoAlterarNomeSacado,
      RetNomeSacadoAlterado,
      RetRecebimentoInstrucaoAlterarEnderecoSacado,
      RetEnderecoSacadoAlterado,
      RetEncaminhadoACartorio,
      RetRetiradoDeCartorio,
      RetRecebimentoInstrucaoDispensarJuros,
      RetJurosDispensados,
      RetManutencaoTituloVencido,
      RetRecebimentoInstrucaoAlterarTipoCobranca,
      RetTipoCobrancaAlterado,
      RetDespesasProtesto,
      RetDespesasSustacaoProtesto,
      RetDebitoCustasAntecipadas,
      RetCustasCartorioDistribuidor,
      RetCustasEdital,
      RetProtestoOuSustacaoEstornado,
      RetDebitoTarifas,
      RetAcertoDepositaria,
      RetOutrasOcorrencias

    }
}
