//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoletoNet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Html {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Html() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoletoNet.Html", typeof(Html).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barra {
            get {
                object obj = ResourceManager.GetObject("barra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barrainterna {
            get {
                object obj = ResourceManager.GetObject("barrainterna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;rBb&quot;&gt;
        ///						&lt;td class=&quot;Ac ld&quot; colspan=&quot;4&quot;&gt;Demonstrativo&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;ct&quot;&gt;
        ///					&lt;td class=&quot;w62&quot;&gt;&lt;/td&gt;
        ///					&lt;td class=&quot;w62&quot;&gt;&lt;/td&gt;
        ///					&lt;td class=&quot;w62&quot;&gt;&lt;/td&gt;
        ///					&lt;td class=&quot;w62&quot;&gt;&lt;/td&gt;				
        ///					@ITENSDEMONSTRATIVO
        ///			&lt;/tr&gt;							
        ///		&lt;/table class=&quot;rBb td&quot;&gt;	
        ///		&lt;table class=&quot;ctN w666&quot;&gt;
        ///				&lt;tr class=&quot;h13&quot;&gt;&lt;td /&gt;&lt;/tr&gt;
        ///				&lt;tr&gt;&lt;td class=&quot;Ar&quot;&gt;Corte na linha pontilhada&lt;/td&gt;&lt;/tr&gt;
        ///				&lt;tr&gt;&lt;td class=&quot;cut&quot; /&gt;&lt;/tr&gt;
        ///		&lt;/table&gt;				
        ///		.
        /// </summary>
        internal static string CabecalhoTabelaDemonstrativo {
            get {
                return ResourceManager.GetString("CabecalhoTabelaDemonstrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///						&lt;tr&gt;
        ///								&lt;td valign=&quot;top&quot;&gt;
        ///										&lt;table class=&quot;150&quot;&gt;
        ///												&lt;tr class=&quot;BHead&quot;&gt;
        ///														&lt;td class=&quot;imgLogo Al&quot;&gt;
        ///															&lt;img src=&quot;@URLIMAGEMLOGO&quot; /&gt;
        ///														&lt;/td&gt;
        ///												&lt;/tr&gt;
        ///										&lt;/table&gt;
        ///										&lt;table class=&quot;w150&quot;&gt;
        ///												&lt;tr class=&quot;ct h13 At&quot;&gt;
        ///														&lt;td class=&quot;w298&quot;&gt;
        ///																Beneficiário
        ///														&lt;/td&gt;
        ///												&lt;/tr&gt;
        ///												&lt;tr class=&quot;cp h12 At rBb&quot;&gt;
        ///														 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Carne {
            get {
                return ResourceManager.GetString("Carne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr&gt;
        ///						&lt;td class=&quot;cpN BT1 Ar&quot;&gt;Comprovante de Entrega&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega1 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;BHead&quot;&gt;
        ///						&lt;td class=&quot;imgLogo Al&quot;&gt;&lt;img src=&quot;@URLIMAGEMLOGO&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w65 Ab bc Ac&quot;&gt;@CODIGOBANCO-@DIGITOBANCO&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w500 Ar ld&quot; valign=&quot;bottom&quot;&gt;Comprovante de Entrega&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega2 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w298&quot;&gt;Beneficiário&lt;/td&gt;
        ///						&lt;td class=&quot;w126&quot;&gt;Agência / Código do Cedente&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Vencimento&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Nº do Documento&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@CEDENTE&lt;/td&gt;
        ///						&lt;td&gt;@AGENCIACODIGOCEDENTE&lt;/td&gt;
        ///						&lt;td&gt;@DATAVENCIMENTO&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@NUMERODOCUMENTO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega3 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w298&quot;&gt;Pagador&lt;/td&gt;
        ///						&lt;td class=&quot;w126&quot;&gt;Carteira / Nosso Número&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Espécie&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Valor do Documento&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@SACADO&lt;/td&gt;
        ///						&lt;td&gt;@NOSSONUMERO&lt;/td&gt;
        ///						&lt;td&gt;@ESPECIE&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@=VALORDOCUMENTO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega4 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w544&quot;&gt;Local de pagamento&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Data de Processamento&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@LOCALPAGAMENTO&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@DATAPROCESSAMENTO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega5 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w150&quot;&gt;Recebi(emos) o bloqueto&lt;/td&gt;
        ///						&lt;td class=&quot;w104&quot;&gt;Data&lt;/td&gt;
        ///						&lt;td class=&quot;w164&quot;&gt;Assinatura&lt;/td&gt;
        ///						&lt;td class=&quot;w105&quot;&gt;Data&lt;/td&gt;
        ///						&lt;td class=&quot;w106&quot;&gt;Entregador&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td /&gt;
        ///						&lt;td /&gt;
        ///						&lt;td /&gt;
        ///						&lt;td /&gt;
        ///						&lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ComprovanteEntrega6 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ctN&quot;&gt;
        ///						&lt;td class=&quot;w666 pL6&quot;&gt;Motivo de não entrega (para uso da empresa entregadora)&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr&gt;
        ///						&lt;td&gt;
        ///								&lt;table class=&quot;cpN w666&quot;&gt;
        ///										&lt;tr&gt;
        ///												&lt;td class=&quot;w104 pL6&quot;&gt;(&amp;nbsp;&amp;nbsp;)&amp;nbsp;Mudou-se&lt;/td&gt;
        ///												&lt;td class=&quot;w104&quot;&gt;(&amp;nbsp;&amp;nbsp;)&amp;nbsp;Ausente&lt;/td&gt;
        ///												&lt;td&gt;(&amp;nbsp;&amp;nbsp;)&amp;nbsp;Não existe n. indicado&lt;/td&gt;
        ///												&lt;td&gt;(&amp;nbsp;&amp;nbsp;)&amp;nbsp;Recusado&lt;/td&gt;
        ///												&lt;td class=&quot;w104&quot;&gt;(&amp;nbsp;&amp;nbsp;)&amp;nbsp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComprovanteEntrega7 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///	 &lt;tr class=&quot;ctN&quot;&gt;
        ///			&lt;td class=&quot;w666 pL6&quot;&gt;Observações (para uso da empresa entregadora)&lt;/td&gt;
        ///	 &lt;/tr&gt;
        ///	 &lt;tr&gt;
        ///			&lt;td&gt;
        ///				 &lt;table class=&quot;cpN w666&quot;&gt;
        ///						&lt;tr&gt;
        ///							 &lt;td class=&quot;w104 pL6&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td class=&quot;w104&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td class=&quot;w104&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///						&lt;/tr&gt;
        ///						&lt;tr&gt;
        ///							 &lt;td class=&quot;pL6&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///							 &lt;td&gt;&amp;nbsp;&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComprovanteEntrega71 {
            get {
                return ResourceManager.GetString("ComprovanteEntrega71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corte {
            get {
                object obj = ResourceManager.GetObject("corte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///				&lt;tr class=&quot;ct&quot;&gt;
        ///					&lt;td class=&quot;cp&quot;&gt;@DESCRICAOGRUPO&lt;/td&gt;
        ///					&lt;td&gt;@DESCRICAOITEM&lt;/td&gt;
        ///					&lt;td&gt;@REFERENCIAITEM&lt;/td&gt;
        ///					&lt;td&gt;@VALORITEM&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		.
        /// </summary>
        internal static string GrupoDemonstrativo {
            get {
                return ResourceManager.GetString("GrupoDemonstrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;cpN&quot;&gt;
        ///						&lt;td class=&quot;At Ac&quot;&gt;@TITULO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;ti&quot;&gt;
        ///						&lt;td class=&quot;At Ac&quot;&gt;@INSTRUCAO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string Instrucoes {
            get {
                return ResourceManager.GetString("Instrucoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ponto {
            get {
                object obj = ResourceManager.GetObject("ponto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;ctN w666&quot;&gt;
        ///				&lt;tr&gt;
        ///						&lt;td class=&quot;w666&quot; /&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;Corte na linha pontilhada&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr&gt;
        ///						&lt;td class=&quot;cut&quot; /&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;
        ///		&lt;br /&gt;.
        /// </summary>
        internal static string ReciboCedenteParte0 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;BHead&quot;&gt;
        ///						&lt;td class=&quot;imgLogo Al&quot;&gt;&lt;img src=&quot;@URLIMAGEMLOGO&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w65 Ab bc Ac&quot;&gt;@CODIGOBANCO-@DIGITOBANCO&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w500 Ar ld&quot; valign=&quot;bottom&quot;&gt;@LINHADIGITAVEL&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte1 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666 ctN&quot;&gt;
        ///				&lt;tr&gt;
        ///						&lt;td class=&quot;pL6  w409&quot;&gt;Sacador / Avalista: @AVALISTA&lt;/td&gt;
        ///						&lt;td class=&quot;w250 Ar&quot;&gt;Autenticação mecânica - &lt;b class=&quot;cpN&quot;&gt;Ficha de Compensação&lt;/b&gt;&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte10 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr&gt;
        ///						&lt;td class=&quot;EcdBar Al pL10&quot;&gt;@IMAGEMCODIGOBARRA&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte11 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;ctN w666&quot;&gt;
        ///				&lt;tr&gt;&lt;td class=&quot;Ar&quot;&gt;Corte na linha pontilhada&lt;/td&gt;&lt;/tr&gt;
        ///				&lt;tr&gt;&lt;td class=&quot;cut&quot; /&gt;&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte12 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w472&quot;&gt;Local de pagamento&lt;/td&gt;
        ///						&lt;td class=&quot;w180&quot;&gt;Vencimento&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@LOCALPAGAMENTO&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@DATAVENCIMENTO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte2 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w472&quot;&gt;Beneficiário&lt;/td&gt;
        ///						&lt;td class=&quot;w180&quot;&gt;Agência / Código Beneficiário&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@CEDENTE_BOLETO&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@AGENCIACONTA&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte3 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w113&quot;&gt;Data do documento&lt;/td&gt;
        ///						&lt;td class=&quot;w163&quot;&gt;N&lt;u&gt;o&lt;/u&gt; documento&lt;/td&gt;
        ///						&lt;td class=&quot;w62&quot;&gt;Espécie doc.&lt;/td&gt;
        ///						&lt;td class=&quot;w34&quot;&gt;Aceite&lt;/td&gt;
        ///						&lt;td class=&quot;w72&quot;&gt;Data processamento&lt;/td&gt;
        ///						&lt;td class=&quot;w180&quot;&gt;Carteira / Nosso número&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@DATADOCUMENTO&lt;/td&gt;
        ///						&lt;td&gt;@NUMERODOCUMENTO&lt;/td&gt;
        ///						&lt;td&gt;@ESPECIEDOCUMENTO&lt;/td&gt;
        ///						&lt;td&gt;@ACEITE&lt;/td&gt;
        ///						&lt;td&gt;@DATAPROCESSAMENTO&lt;/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReciboCedenteParte4 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w113&quot;&gt;Uso do banco&lt;/td&gt;
        ///						&lt;td class=&quot;w83&quot;&gt;Carteira&lt;/td&gt;
        ///						&lt;td class=&quot;w53&quot;&gt;Espécie&lt;/td&gt;
        ///						&lt;td class=&quot;w123&quot;&gt;Quantidade&lt;/td&gt;
        ///						&lt;td class=&quot;w72&quot;&gt;(x) Valor&lt;/td&gt;
        ///						&lt;td class=&quot;w180&quot;&gt;(=) Valor documento&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@USODOBANCO&lt;/td&gt;
        ///						&lt;td class=&quot;Al&quot;&gt;@CARTEIRA&lt;/td&gt;
        ///						&lt;td class=&quot;Al&quot;&gt;@ESPECIE&lt;/td&gt;
        ///						&lt;td&gt;@QUANTIDADE&lt;/td&gt;
        ///						&lt;td&gt;@VALORDOCUMENTO&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReciboCedenteParte5 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;rc6&quot;&gt;
        ///						&lt;td class=&quot;w478&quot;&gt;
        ///								&lt;div class=&quot;ctN pL10&quot;&gt;Instruções (Texto de responsabilidade do beneficiário)&lt;/div&gt;
        ///                &lt;div class=&quot;cpN pL10 it&quot; style=&quot;height:105px; overflow:hidden&quot;&gt;@INSTRUCOES&lt;/div&gt;                
        ///						&lt;/td&gt;
        ///						&lt;td class=&quot;w186&quot;&gt;
        ///								&lt;div class=&quot;t&quot;&gt;(-) Desconto / Abatimentos&lt;/div&gt;
        ///								&lt;div class=&quot;c BB&quot;&gt;@DESCONTOS&lt;/div&gt;
        ///								&lt;div class=&quot;t&quot;&gt;(-) Outras deduções&lt;/div&gt;
        ///								&lt;div class=&quot;c BB&quot;&gt;@OUTRASDEDUCOES&lt;/div&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReciboCedenteParte6 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReciboCedenteParte7 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w659&quot;&gt;Pagador&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12&quot;&gt;
        ///						&lt;td class=&quot;At&quot;&gt;@SACADO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte8 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;rBb&quot;&gt;
        ///						&lt;td class=&quot;w478 BL&quot;&gt;
        ///								&lt;div class=&quot;cpN pL6&quot;&gt;@INFOSACADO&lt;/div&gt;
        ///						&lt;/td&gt;
        ///						&lt;td class=&quot;Ab BL&quot;&gt;
        ///								&lt;div class=&quot;ctN pL6&quot;&gt;Cód. baixa&lt;/div&gt;
        ///						&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboCedenteParte9 {
            get {
                return ResourceManager.GetString("ReciboCedenteParte9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			&lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;BHead BT2&quot;&gt;
        ///						&lt;td class=&quot;imgLogo Al&quot;&gt;&lt;img src=&quot;@URLIMAGEMLOGO&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w65 Ab bc Ac&quot;&gt;@CODIGOBANCO-@DIGITOBANCO&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w500 Ar ld&quot; valign=&quot;bottom&quot;&gt;RECIBO DO SACADO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///			&lt;/table&gt;				
        ///			&lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td&gt;Local de pagamento&lt;/td&gt;
        ///						&lt;td&gt;&lt;/td&gt;
        ///				&lt;/tr&gt;			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReciboCedenteRelatorioValores {
            get {
                return ResourceManager.GetString("ReciboCedenteRelatorioValores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr&gt;
        ///						&lt;td class=&quot;ctN cut&quot; /&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr&gt;
        ///						&lt;td class=&quot;cpN Ar&quot;&gt;Recibo do Pagador&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte1 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w659&quot;&gt;Beneficiário Endereço / Sacador Avalista: @AVALISTA&lt;/td&gt; 
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td class=&quot;At&quot;&gt;@ENDERECOCEDENTE&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte10 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;BHead&quot;&gt;
        ///						&lt;td class=&quot;imgLogo Al&quot;&gt;&lt;img src=&quot;@URLIMGCEDENTE&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w65 Ab bc Ac&quot;&gt;@CODIGOBANCO-@DIGITOBANCO&lt;/td&gt;
        ///						&lt;td class=&quot;barra&quot;&gt;&lt;img src=&quot;@URLIMAGEMBARRA&quot; /&gt;&lt;/td&gt;
        ///						&lt;td class=&quot;w500 Ar Ab ld&quot;&gt;@LINHADIGITAVEL&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte2 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13 At&quot;&gt;
        ///						&lt;td class=&quot;w298&quot;&gt;Beneficiário&lt;/td&gt;
        ///						&lt;td class=&quot;w126&quot;&gt;Agência / Código do Beneficiário&lt;/td&gt;
        ///						&lt;td class=&quot;w34&quot;&gt;Espécie&lt;/td&gt;
        ///						&lt;td class=&quot;w45&quot;&gt;Quantidade&lt;/td&gt;
        ///						&lt;td class=&quot;w128&quot;&gt;Carteira / Nosso número&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 At rBb&quot;&gt;
        ///						&lt;td&gt;@CEDENTE&lt;/td&gt;
        ///						&lt;td&gt;@AGENCIACODIGOCEDENTE&lt;/td&gt;
        ///						&lt;td&gt;@ESPECIE&lt;/td&gt;
        ///						&lt;td&gt;@QUANTIDADE&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@NOSSONUMERO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte3 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w192&quot;&gt;Número do documento&lt;/td&gt;
        ///						&lt;td class=&quot;w132&quot;&gt;CPF/CNPJ&lt;/td&gt;
        ///						&lt;td class=&quot;w134&quot;&gt;Vencimento&lt;/td&gt;
        ///						&lt;td class=&quot;w180&quot;&gt;Valor documento&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@NUMERODOCUMENTO&lt;/td&gt;
        ///						&lt;td&gt;@CPFCNPJ&lt;/td&gt;
        ///						&lt;td&gt;@DATAVENCIMENTO&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;@=VALORDOCUMENTO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte4 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w113&quot;&gt;(-) Desconto / Abatimentos&lt;/td&gt;
        ///						&lt;td class=&quot;w112&quot;&gt;(-) Outras deduções&lt;/td&gt;
        ///						&lt;td class=&quot;w113&quot;&gt;(+) Mora / Multa&lt;/td&gt;
        ///						&lt;td class=&quot;w113&quot;&gt;(+) Outros acréscimos&lt;/td&gt;
        ///						&lt;td class=&quot;w180&quot;&gt;(=) Valor cobrado&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb Ab&quot;&gt;
        ///						&lt;td&gt;@DESCONTOS&lt;/td&gt;
        ///						&lt;td&gt;@OUTRASDEDUCOES&lt;/td&gt;
        ///						&lt;td&gt;@MORAMULTA&lt;/td&gt;
        ///						&lt;td&gt;@OUTROSACRESCIMOS&lt;/td&gt;
        ///						&lt;td class=&quot;Ar&quot;&gt;&amp;nbsp;@VALORCOBRADO&lt;/td&gt;
        ///				&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReciboSacadoParte5 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ct h13&quot;&gt;
        ///						&lt;td class=&quot;w659&quot;&gt;Pagador&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12&quot;&gt;
        ///						&lt;td&gt;@SACADO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cp h12 rBb&quot;&gt;
        ///						&lt;td&gt;@INFOSACADO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte6 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;w666&quot;&gt;
        ///				&lt;tr class=&quot;ctN h13&quot;&gt;
        ///						&lt;td class=&quot;pL6&quot;&gt;Instruções&lt;/td&gt;
        ///						&lt;td class=&quot;w180 Ar&quot;&gt;Autenticação mecânica&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///				&lt;tr class=&quot;cpN h12&quot;&gt;
        ///						&lt;td class=&quot;pL6 it&quot;&gt;@INSTRUCOES&lt;/td&gt;
        ///						&lt;td class=&quot;pL6 Ar&quot;&gt;@AUTENTICACAOMECANICA&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte7 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;ctN w666&quot;&gt;
        ///				&lt;tr class=&quot;h13&quot;&gt;&lt;td /&gt;&lt;/tr&gt;
        ///				&lt;tr class=&quot;h13&quot;&gt;&lt;td /&gt;&lt;/tr&gt;
        ///				&lt;tr&gt;&lt;td class=&quot;Ar&quot;&gt;Corte na linha pontilhada&lt;/td&gt;&lt;/tr&gt;
        ///				&lt;tr&gt;&lt;td class=&quot;cut&quot; /&gt;&lt;/tr&gt;
        ///				&lt;tr class=&quot;h13&quot;&gt;&lt;td /&gt;&lt;/tr&gt;
        ///				&lt;tr class=&quot;h13&quot;&gt;&lt;td /&gt;&lt;/tr&gt;
        ///		&lt;/table&gt;.
        /// </summary>
        internal static string ReciboSacadoParte8 {
            get {
                return ResourceManager.GetString("ReciboSacadoParte8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///				&lt;tr class=&quot;cp h13 rBb&quot;&gt;
        ///					&lt;td&gt;Total&lt;/td&gt;
        ///					&lt;td&gt;&lt;/td&gt;
        ///					&lt;td&gt;&lt;/td&gt;
        ///					&lt;td&gt;@VALORTOTALGRUPO&lt;/td&gt;
        ///				&lt;/tr&gt;
        ///		.
        /// </summary>
        internal static string TotalDemonstrativo {
            get {
                return ResourceManager.GetString("TotalDemonstrativo", resourceCulture);
            }
        }
    }
}
